packages:
  - 'packages/*'
  - 'packages/dynamo-tables/*'
  - 'packages/common/*'
  - 'packages/smithy/*'
allowBuilds:
  '@swc/core': false
  cpu-features: false
  esbuild: false
  nx: false
  protobufjs: false
  ssh2: false
overrides:
  '@aws/nx-plugin': 'link:../nx-plugin-for-aws/dist/packages/nx-plugin'
