# Defines the checks to skip entirely. Remove if your requirements differ.
skip-check:
  # Lambda function suppressions
  - CKV_AWS_115 # Concurrent execution limit
  - CKV_AWS_116 # Dead Letter Queue
  - CKV_AWS_117 # Lambda functions in VPC
  - CKV_AWS_173 # Encrypt Lambda environment variables
  - CKV_AWS_272 # Code signing
  - CKV_AWS_7   # Key rotation
  - CKV_AWS_86  # CloudFront Access Logging
  - CKV_AWS_68  # CloudFront WAF
  - CKV_AWS_18  # S3 Access Logging
  - CKV_AWS_158 # CloudFront Log Group encryption
  - CKV_AWS_96  # Aurora encryption
  - CKV_AWS_149 # Secrets Manager encryption
output:
  - cli
  - json
output-file-path: console,dist/packages/infra/checkov/checkov_report.json
