/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostgresEntitiesRouteImport } from './routes/postgres-entities'
import { Route as MysqlEntitiesRouteImport } from './routes/mysql-entities'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'

const PostgresEntitiesRoute = PostgresEntitiesRouteImport.update({
  id: '/postgres-entities',
  path: '/postgres-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const MysqlEntitiesRoute = MysqlEntitiesRouteImport.update({
  id: '/mysql-entities',
  path: '/mysql-entities',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/mysql-entities': typeof MysqlEntitiesRoute
  '/postgres-entities': typeof PostgresEntitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/mysql-entities': typeof MysqlEntitiesRoute
  '/postgres-entities': typeof PostgresEntitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/mysql-entities': typeof MysqlEntitiesRoute
  '/postgres-entities': typeof PostgresEntitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent' | '/mysql-entities' | '/postgres-entities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent' | '/mysql-entities' | '/postgres-entities'
  id: '__root__' | '/' | '/agent' | '/mysql-entities' | '/postgres-entities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  MysqlEntitiesRoute: typeof MysqlEntitiesRoute
  PostgresEntitiesRoute: typeof PostgresEntitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/postgres-entities': {
      id: '/postgres-entities'
      path: '/postgres-entities'
      fullPath: '/postgres-entities'
      preLoaderRoute: typeof PostgresEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysql-entities': {
      id: '/mysql-entities'
      path: '/mysql-entities'
      fullPath: '/mysql-entities'
      preLoaderRoute: typeof MysqlEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  MysqlEntitiesRoute: MysqlEntitiesRoute,
  PostgresEntitiesRoute: PostgresEntitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
