/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamePlayerNameRouteImport } from './routes/game/$playerName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayerNameRoute = GamePlayerNameRouteImport.update({
  id: '/game/$playerName',
  path: '/game/$playerName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$playerName': typeof GamePlayerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$playerName': typeof GamePlayerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$playerName': typeof GamePlayerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$playerName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$playerName'
  id: '__root__' | '/' | '/game/$playerName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamePlayerNameRoute: typeof GamePlayerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$playerName': {
      id: '/game/$playerName'
      path: '/game/$playerName'
      fullPath: '/game/$playerName'
      preLoaderRoute: typeof GamePlayerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamePlayerNameRoute: GamePlayerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
